### ISSUE TITLE
Security error on systems configured to enforce FIPS

### ISSUE THREAD

**Issue by StephenCWills** [GridProtectionAlliance/openHistorian#22]
![image](https://cloud.githubusercontent.com/assets/9203145/24277908/b575d3b0-1016-11e7-9746-680779f4f74e.png)

**Comment by StephenCWills** [comment]
Quoted from Ritchie:

> Our primary security algorithms account for this by automatically switching to FIPS security mode, i.e., using non-managed OS-level security algorithms. The fully managed versions are not FIPS certified like the ones at the OS level.
> 
> Looks like we will need to adapt openHistorian security code to make this assertion…

**Comment by ritchiecarroll** [comment]
This has been fixed
