### ISSUE TITLE
Manager Start Menu Link Broken After Upgrade from 2.2

### ISSUE THREAD

**Issue by chefsteph9** [GridProtectionAlliance/openHistorian#27]
If version 2.2 of the openHistorian is installed and you upgrade to the [nightly build](http://www.gridprotectionalliance.org/NightlyBuilds/openHistorian/Beta/openHistorian.Installs.zip), the start menu link for openHistorian Manager is broken.  
The openHistorian Manager can still be started from C:\Program Files\openHistorian, and all other start menu links are working.  
This does not happen when you do a fresh install from either the [latest release](https://github.com/GridProtectionAlliance/openHistorian/releases/download/v2.2/openHistorian.Installs.zip) or the [nightly build](http://www.gridprotectionalliance.org/NightlyBuilds/openHistorian/Beta/openHistorian.Installs.zip). It only happens on an upgrade.

**Comment by ritchiecarroll** [comment]
Closing this for now, esp with release of 2.5 - let me know if you have any further issues.
