### ISSUE TITLE
The data become "NAN"

### ISSUE THREAD

**Issue by HeYin1** [GridProtectionAlliance/openHistorian#29]
I am trying to add a new PMU to Openhistorian. 
It can be connected through PMU tester and can be connected to OpenHistorian. However, the data become "NAN". 
Then I try to use OpenPDC, the data is correct which really make me confused.

Can anyone help me with this issue?

Best regards,

He Yin

![openhistorian_nan data](https://user-images.githubusercontent.com/31247678/30502747-8782a4ca-9a35-11e7-9cd1-22eab9994cdd.png)
![openpdc](https://user-images.githubusercontent.com/31247678/30502830-e731b71c-9a35-11e7-8754-d502d0620dee.png)

**Comment by ritchiecarroll** [comment]
I think this is a bug in the manager that has been fixed. Have you tried installing the Nightly Build?

See here: http://www.gridprotectionalliance.org/nightlybuilds/openHistorian/Beta/openHistorian.Installs.zip

Thanks!
Ritchie
