### ISSUE TITLE
Data Validation

### ISSUE THREAD

**Issue by FerriadWang** [GridProtectionAlliance/openHistorian#34]
Hi,

I have a question regarding the .d2 file naming. It seems the openHistorian cannot prevent a too old or too new data from coming in? Please see attached.
![image](https://user-images.githubusercontent.com/7548029/34010874-295af0ee-e0dc-11e7-8ff4-d9fa175e73d8.png)

Here in the image, you can find some .d2 file contains the timestamp many years later, but I would assume this should not be inserted into the database?

**Comment by ritchiecarroll** [comment]
The latest version of the openHistorian includes settings to throw out very old or future data:

![image](https://user-images.githubusercontent.com/9202752/34058151-f3c57f86-e1a7-11e7-938d-70b713df3324.png)
