### ISSUE TITLE
PIAdapter not loaded

### ISSUE THREAD

**Issue by FerriadWang** [GridProtectionAlliance/openHistorian#35]
Hi, I am using the openHistorian 2.4 release version and I found the Pi adapter no longer appears in the openHistorian Manager. However, I do find the PIAdapter.dll exists in the installation folder. Not sure if you are aware of this issue.
![image](https://user-images.githubusercontent.com/7548029/34891762-c61b5b6a-f7a4-11e7-9cfe-ea96edb93214.png)
![image](https://user-images.githubusercontent.com/7548029/34891827-017f33fc-f7a5-11e7-9718-851115f910b0.png)

**Comment by ritchiecarroll** [comment]
It usually only shows up if the PI-AFSDK is also installed on the same system

**Comment by ritchiecarroll** [comment]
Is this still an issue?

**Comment by FerriadWang** [comment]
Sorry for the late reply. It is resolved. Thank you!
