### ISSUE TITLE
Openhistorian Manager crash

### ISSUE THREAD

**Issue by pietropau** [GridProtectionAlliance/openHistorian#36]
Hi,
after upgrade from version 2.2 to 2.4, openhistorian_manager crash, see file attached.

[error_OpenHistorian.txt](https://github.com/GridProtectionAlliance/openHistorian/files/1829062/error_OpenHistorian.txt)

regards
Pietro

**Comment by ritchiecarroll** [comment]
Will you see if the nightly build has the same issue:
http://www.gridprotectionalliance.org/nightlybuilds/openHistorian/Beta/openHistorian.Installs.zip

Thanks,
Ritchie

**Comment by ritchiecarroll** [comment]
Closing this for now, esp with release of 2.5 - let me know if you have any further issues.
