### ISSUE TITLE
Grafana Abnormality

### ISSUE THREAD

**Issue by FerriadWang** [GridProtectionAlliance/openHistorian#38]
Hi,
I find the built-in Grafana would fail to grab data from the openHistorian. 
I am able to grab the real-time/historian frequency data from the .d2 files and I can see the data is streaming in the historian manager, but I am not able to visualize the data on Grafana. Is there any known issue about this?

**Comment by ritchiecarroll** [comment]
Not that I am aware of - could be security related - have you tried restarting the openHistorian service?

**Comment by FerriadWang** [comment]
I tried restarting the service but it didn't help. It's weird that I can use the same format FILTER command to visualize the data of another interconnection (just change the value after '=').

**Comment by ritchiecarroll** [comment]
Have you tried the latest build:
http://www.gridprotectionalliance.org/nightlybuilds/openHistorian/Beta/openHistorian.Installs.zip

**Comment by ritchiecarroll** [comment]
Closing this for now, esp with release of 2.5 - let me know if you have any further issues.
