### ISSUE TITLE
OPENHISTORIAN NAVIGATION

### ISSUE THREAD

**Issue by Vtern** [GridProtectionAlliance/openHistorian#4]
Good morning,

I'm new of OpenPdc and OpenHistorian, so I ask for your help while reading all the pages of documentation, issues and discussions. 
My questions are very simple and I attach them in the following:

1) Is OpenPdC independent from OpenHistorian? I mean that I noticed that the mask interface is very similar, hence the data saving is ensured even if OpenpdC is not running?

2) I used "Historian Playback/Export Utility" while the export process is quite stable (except when you choose "Process data at XX samples per second") I'm would know it has an associated data viewer tool which permits to navigate the database ("Historian Playback" name seems intuitive that there is this possibility) as the analyst wants (for instance select all the trigger of overfrequency in the past or similar)

3) Could you confirm that the "STAT measurements" of OpenPdc are not stored in OpenHistorian? Which quantities/variables are hence stored as default apart PMUs signals? This is a very crucial issue in selecting the most appropriate storage capacity...

Thanks for a kind reply

V

**Comment by ritchiecarroll** [comment]
Please move product questions to discussion board: http://discussions.gridprotectionalliance.org/c/gpa-products/openhistorian
