### ISSUE TITLE
Does the “openHistorian” have necessary redundancy?

### ISSUE THREAD

**Issue by zhouyijiaren** [GridProtectionAlliance/openHistorian#40]
Whether the system consider the “High availability” or not?when the computer is shutdown,the system can save the data and the database client can save the data by itself.Does this project have such function?

**Comment by ritchiecarroll** [comment]
When used in conjunction with the substationSBG, for example, yes:

![image](https://user-images.githubusercontent.com/9202752/44415891-7e94be00-a53f-11e8-8047-285293a48693.png)

**Comment by ritchiecarroll** [comment]
Let me know if you have any more questions about this feature, but I am going to go ahead and close this issue for now...

Thanks!
Ritchie
