### ISSUE TITLE
What about the performance of the OpenHistorian?

### ISSUE THREAD

**Issue by zhouyijiaren** [GridProtectionAlliance/openHistorian#41]
What about the performance of the OpenHistorian?

**Comment by ritchiecarroll** [comment]
What exactly would you like to know about performance?

**Comment by saelwahid** [comment]
Hi
I was able to connect to the PMU in SEL-421 relay using the pmu connection tester, but I wasn't able to connect the open historian 2, its giving me this error (connection attempt failed)
would you please show me the right steps to add a new input device, I tried the synchrophasor walk through wizard but nothing changed

**Comment by ritchiecarroll** [comment]
(1) If you have successfully connected with PMU Connection Tester, you can save the connection information into a file by selecting "File > Connection > Save..." from the main menu:
![image](https://user-images.githubusercontent.com/9202752/46873819-9254f600-ce05-11e8-99d7-88394184e3ea.png)

By default this will create a file with an extension of ".PmuConnection" - this is an XML file that contains the connection information you used in PMU Connection Tester to connect to your PMU.

(2) Now, from the "openHistorian Manager" - the desktop application, not the web app - click on the "Input Device Wizard" button on the home page (or navigate to "Inputs > Synchrophasor Device Wizard" from the main menu):
![image](https://user-images.githubusercontent.com/9202752/46874020-2a52df80-ce06-11e8-8be5-437f4e696d08.png)

(3) Click "OK" on the "Welcome to Wizard Walkthrough!" front page and answer "Yes" to the "Have you tested your device's connection settings using the PMU Connection Tester?" question. Also answer "Yes" to "Do you have a connection file from the PMU Connection Tester" question.

(4) You should now be on a screen that says "Please enter the path to the connection file from the PMU Connection Tester." - from here click on the "Browse" button and select the ".PmuConnection" file you created in step (1):
![image](https://user-images.githubusercontent.com/9202752/46874240-b95ff780-ce06-11e8-8ccc-b43fe9a2f62b.png)

(5) Click "OK" once the file has been selected and the click "Yes" in response to "Would you like the wizard to attempt to make this connection?". On the next screen click "Request Configuration" to attempt the connection to the device.

(6) Assuming the connection is successful, provide any ancillary requested information on the next one or two screens and click "OK" on each - then on the final wizard screen click "Finish":
![image](https://user-images.githubusercontent.com/9202752/46874577-77838100-ce07-11e8-81e3-099fc18edd6b.png)

(6) Now clicking "Finish" on the bottom right of the screen will complete adding the device to the openHistorian. You can now navigate to the "Graph Measurements" screen to verify that data is flowing into the historian by clicking "Monitoring > Graph Measurements" from the main menu:
![image](https://user-images.githubusercontent.com/9202752/46874760-e6f97080-ce07-11e8-9275-d58a5af934c1.png)

(7) Additionally, you shouw now find the data in the openHistorian web application ready for trending and export:
![image](https://user-images.githubusercontent.com/9202752/46874898-4ce5f800-ce08-11e8-8e70-b0b0d51ab33c.png)

![image](https://user-images.githubusercontent.com/9202752/46874968-7737b580-ce08-11e8-8588-4023351f1ea0.png)

**Comment by saelwahid** [comment]
its still giving me the connection failed error 

![error message](https://user-images.githubusercontent.com/42352898/46876464-6426e480-ce0c-11e8-96a5-9b5a6892e84c.png)

I attached the error message I had
