### ISSUE TITLE
Custom adapters and data archiving stopped 

### ISSUE THREAD

**Issue by FerriadWang** [GridProtectionAlliance/openHistorian#44]
Hey guys,

I am using openistorian 2.3.7 version and for some reason, it stopped writing data to the archive and my action adapters were stopped as well. I checked the logs and it seems the system somehow stopped processing the measurements.
![image](https://user-images.githubusercontent.com/7548029/51627413-f9f40480-1f0f-11e9-9af5-bca8db923d08.png)
After a while, it kind of resumed to process the measurements but still abnormal.
![image](https://user-images.githubusercontent.com/7548029/51627497-48a19e80-1f10-11e9-9f11-d5f1a1be995d.png)
Is this a known issue?

**Comment by ritchiecarroll** [comment]
Can you try a later build? New release version is up to v2.6. Thanks!
