### ISSUE TITLE
API to query measurement details

### ISSUE THREAD

**Issue by Xinya-Li** [GridProtectionAlliance/openHistorian#45]
https://github.com/GridProtectionAlliance/SIEGate/blob/master/Source/Documentation/wiki/Creating_Internal_Gateway_Connections.md

According to the example API showed, I create a API to read data from OpenHistorian. However, the data can only be read according to PointID, which is 1, 2, 3, .....
Because it is really hard to tell which signal it is according to PointID, more information is needed.
Is there a way that the details of measurements can be queried at the same time? For example , the signal names ( e.g. TVA_TESTDEVICE: ABBS ).

**Comment by ritchiecarroll** [comment]
Lots of ways to get data out of openHistorian - the best way for exports is to use the built-in web interface http://localhost:8180/ and use the Trend/Export screen.

There is a data export tool installed with the openHistorian as well called the `Data Extraction Utility` - run the `DataExtractionUtility.exe` from the install folder.

Can also use GEP data extraction utility.

If you want to use the native openHistorian API, look to HistorianDataWalker for an example:
https://github.com/GridProtectionAlliance/HistorianDataWalker

There are also web api's included for data extraction - including the one used by Grafana...

Hope that helps!
Ritchie
