### ISSUE TITLE
Adding New Device (hardware PMU)

### ISSUE THREAD

**Issue by arz-ece** [GridProtectionAlliance/openHistorian#55]
Hello Everyone,

I am trying to ADD DEVICE in openHistorian 2.0 portal, so that I can retrieve data seamlessly instead of using the conventional Historian Playback Utility software. 

The problem I have is that **it does not allow me to Save Device (not clickable)**, even after I assign all the Phase quantities in red in picture below! 

The connection file is for a hardware PMU that has been tested with PMU tester and is in use with OpenPDC2.7. I appreciate any help on this.  

![OpenHistorian2_AddingDeviceIssue](https://user-images.githubusercontent.com/60282375/73759372-e0e47d00-4739-11ea-8bb1-b17162d9b040.png)

Thanks,
Ali

**Comment by ritchiecarroll** [comment]
So long as there are errors on the screen, you will not be able to click "Save". You will need set the "Phase" to a valid value for each the voltages and currents.

BTW, we have improved the algorithm to "guess" the phase based on common PMU phasor labels and this will be in the next openHistorian release coming out soon.

**Comment by arz-ece** [comment]
Thank you Ritchie for the information, but I had put all phases to a valid value before and the problem still prevailed.

**Comment by ritchiecarroll** [comment]
If there is no "red errors" then the "Save" button should be enabled. You can also press "F12" on the browser to see if there are any reported errors.

**Comment by arz-ece** [comment]
I ran this on Internet Explorer instead of Chrome browser and this is the Error I got:

![image](https://user-images.githubusercontent.com/60282375/73787386-2e2c1300-4769-11ea-8ee3-313f7e524eee.png)

**Comment by ritchiecarroll** [comment]
I think on IE that may be a normal message. Did Chrome report any messages?

**Comment by arz-ece** [comment]
> I think on IE that may be a normal message. Did Chrome report any messages?

Chrome did not report any error messages.

**Comment by ritchiecarroll** [comment]
Since this new web-based UI for adding devices is giving you trouble, I suggest using the "openHistorian Manager" _application_ than can be found on the start menu.

Just use the new device wizard to add a new device.

Thanks,
Ritchie

**Comment by arz-ece** [comment]
Thank you for the prompt reply Ritchie. I have the following problem with the OpenHistorian Manager. I had even stopped OpenPDC and tried to add device, but still same error!

![OpenHistorianManager_Error](https://user-images.githubusercontent.com/60282375/73854236-2b303180-4800-11ea-9c2d-803909a624ac.PNG)

**Comment by ritchiecarroll** [comment]
I though the web page just wouldn't allow you to press the `Save` button, did you see this same error message on the web interface?

Anyway, this message says to cannot connect to device. Does PMU Connection Tester connect to target device OK? You can download tool from here:

https://github.com/GridProtectionAlliance/PMUConnectionTester/releases

Thanks,
Ritchie

**Comment by ritchiecarroll** [comment]
FYI - I am closing this issue as this seems like more of a usability issue than a software problem.

Please feel continue this conversation at our discussions board for assistance with software usage:

https://discussions.gridprotectionalliance.org/c/gpa-products/openhistorian

Thanks!
Ritchie
